services:
  iceberg:
    build:
      context: .
      dockerfile: Dockerfile
    image: iceberg:dev
    container_name: iceberg
    restart: unless-stopped
    network_mode: host
    tty: true
    environment:
      - PUID=0
      - PGID=0
      - ORIGIN=http://localhost:3000
      - TZ=America/New_York
    volumes:
      - ./data:/iceberg/data
      - /mnt:/mnt
